### PR TITLE
Dependency: Add PCRE library to the repo in order to build SWIG

### PR DESCRIPTION
**Pull request by QuantamHD**
This PR will enable us to add swig which is a precursor to build OpenROAD.

### CODE REVIEW

**Comment by hzeller** [comment]
Are the pcre sources coming from somewhere else ? I only see the `config.h` and `pcre.h`. Or do I misunderstand how the bzl rule works ?

**Comment by QuantamHD** [comment]
In bazel land you use workspace rules to pull in the majority of the srcs.

dependency_support/org_pcre_ftp/org_pcre_ftp.bzl

**Comment by jesec** [comment]
https://github.com/hdl/bazel_rules_hdl/blob/354915d8c00948cbbf299263913db40caa141e17/dependency_support/org_pcre_ftp/org_pcre_ftp.bzl#L20-L30

**Comment by hzeller** [comment]
Oh, I see, the part in the `org_pcre_ftp.bzl` is essentially the WORKSPACE snippet.

**Review by hzeller — APPROVED** [review]

**Pull request merged**
