### PR TITLE
dependency_support/boost: switch lzma to a safer repo

### PR DESCRIPTION
**Pull request by proppy**
Rebase https://github.com/nelhage/rules_boost/pull/556 on top of https://github.com/nelhage/rules_boost/commit/1217caae292dc9f14e8109777ba43c988cf89c5b.

Context:
https://github.com/nelhage/rules_boost/issues/555
https://www.openwall.com/lists/oss-security/2024/03/29/4

### CODE REVIEW

**Comment by ericastor** [comment]
Don't we need to update the `shallow_since` line too?

**Comment by proppy** [comment]
PTAL

**Review by ericastor — APPROVED** [review]
Looks good to me as a quick fix - let's let the build finish before merging, but we're good to go otherwise.

**Comment by QuantamHD** [comment]
Thanks @ericastor and @proppy

**Comment by ericastor** [comment]
Tests are failing; looks like we need to update the pip dependency files.

**Pull request merged**
