### PR TITLE
Remove the unused implicit attribute `_cc_toolchains`.

### PR DESCRIPTION
**Pull request by mikesinouye**
CC toolchains are gathered from the line:
```
toolchains = use_cc_toolchains(),
```

### CODE REVIEW

**Comment by katre** [comment]
Can your project upgrade to Bazel 7.4.1? That should resolve the failure, and is much more up-to-date than the current vevrsion of 6.x.

**Comment by mikesinouye** [comment]
While that is the best fix, briefly experimenting with bazel 7 seems like it requires a cascade of dependency upgrades/fixes. At this point, the time is likely better spent upgrading to bzlmod instead. @QuantamHD should we stick with bazel6 for now, resolve our internal issue with a patch, and plan to spend time for a proper bazel 8 + bzlmod migration sometime next year?

**Comment by QuantamHD** [comment]
Might want to just go with a patch internally, and move to bzlmod

**Comment by mikesinouye** [comment]
Sounds good, let's go with that.

**Pull request closed without merging**
