### PR TITLE
dependency_support/com_icarus_iverilog: bump version

### PR DESCRIPTION
**Pull request by proppy**
required by https://github.com/google/xls/pull/726

### CODE REVIEW

**Comment by mithro** [comment]
@proppy - Is this pull request worth rebasing and landing now?

**Comment by proppy** [comment]
＠mithro this needs to be rebase against internal `BUILD` file changes (the iverilog project file structure changed quite a bit in 5 years)

**Comment by proppy** [comment]
Looks like cocotb tests fail because of the way `vvp` and `iverilog` are invoked:
```
Step #1: //cocotb/tests:cocotb_counter                                            FAILED in 0.3s
```

**Review by QuantamHD — APPROVED** [review]

**Pull request merged**
