### PR TITLE
Use `-no_pie` for darwin builds

### LINKED ISSUE #140: Build failure on Mac OS due to `ld -no-pie`
I'm trying to build [XLS](https://github.com/google/xls) on Mac OS from source which pulls rules_hdl as a dependency and the build seems to fail with the following error:
```
ERROR: /private/var/tmp/b3261ecaf5b6ec09d8051d16006b13a8/external/com_icarus_iverilog/BUILD.bazel:351:10: Linking external/com_icarus_iverilog/ivl failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target @com_icarus_iverilog//:ivl) external/llvm_toolchain/bin/cc_wrapper.sh @bazel-out/darwin-opt/bin/external/com_icarus_iverilog/ivl-2.params
```

Digging into it, it seems that `ld` on mac has the option `-no_pie` instead of `-no-pie` used here:
https://github.com/hdl/bazel_rules_hdl/blob/main/dependency_support/com_icarus_iverilog/bundled.BUILD.bazel#L375

I'm not super familiar with bazel but if there is an obvious fix, I can try to write up a PR

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #140

### CODE REVIEW

**Comment by rachitnigam** [comment]
CC @QuantamHD

**Comment by QuantamHD** [comment]
Does this fix the XLS build problem?

**Comment by rachitnigam** [comment]
Sorry to poke you again @QuantamHD, just added the `-Wl` in front of the flags. Can you fire off the CI again?

**Comment by rachitnigam** [comment]
This seems to fix the XLS failure as well!

**Comment by rachitnigam** [comment]
@QuantamHD I think this is good to merge! I can ping the XLS folks to change their SHA-commit dependency once this is merged

**Comment by QuantamHD** [comment]
Done.

**Pull request merged**
