### PR TITLE
Updates test ciremote to try to get test logs on build buddy.

### PR DESCRIPTION
**Pull request by QuantamHD**

### CODE REVIEW

**Comment by ericastor** [comment]
Looks like it's not quite correct, though I don't know why...

```
java.io.IOException: Failed to fetch file with hash 'f15e5b0343a74dc16278dd43f49bcd3417bdf09c28cb63d9e6cb8f5d9c7da556' because it does not exist remotely. --remote_download_outputs=minimal does not work if your remote cache evicts files during builds.
```

I'm not sure why it's trying to download anything... but maybe it needs an API key?

**Comment by mithro** [comment]
`Step #1: WARNING: option '--remote_cache' was expanded to from both option '--config=ciremotebuild' (source command line options) and option '--config=ciremotebuild' (source command line options)`

**Comment by mithro** [comment]
So you seem to be using different caches for building verse testing?

**Comment by mithro** [comment]
`build:ciremotebuild --remote_cache=https://storage.googleapis.com/bazel-cache-rules-hdl`
verses
`test:ciremotebuild --remote_cache=grpcs://cloud.buildbuddy.io`

**Comment by QuantamHD** [comment]
I'm not sure to be honest

**Review by mithro — APPROVED** [review]
It seems to work....

**Pull request merged**
