### PR TITLE
Updated Verilator to not reply on system python

### PR DESCRIPTION
**Pull request by abrisco**
In my remote executor image I explicitly don't want `python`/`python3` to appear on PATH and to instead rely on toolchains defined in Bazel to correctly match an interpreter. I noticed there were some genrules when building Verilator that were relying on this behavior. I've replaced the genrules used by Verilator with proper rules and `py_binary` targets to make builds more hermetic.

### CODE REVIEW

**Comment by QuantamHD** [comment]
Running CI. Thanks for the contribution

**Comment by QuantamHD** [comment]
Can you resolve the merge conflict. Otherwise looks good

**Comment by abrisco** [comment]
@QuantamHD rebased!

**Comment by abrisco** [comment]
@QuantamHD Looks like CI is passing 😃

**Review by QuantamHD — APPROVED** [review]

**Review by QuantamHD — APPROVED** [review]

**Pull request merged**
