### PR TITLE
Some minor cleanups

### PR DESCRIPTION
**Pull request by nanavati**

### CODE REVIEW

**Comment by mithro** [comment]
@nanavati - I sent you an invite to this repo so that CI will run automatically on your pull requests.

**Comment by nanavati** [comment]
@mithro Thanks!

Now that I've accepted the invite, what's the best way for me to retrigger the CI run?

**Comment by QuantamHD** [comment]
You can run /gcbrun

**Comment by QuantamHD** [comment]
LGTM

**Pull request merged**
