### PR TITLE
$(PYTHON3) Make variable substitution is not supported in run_shell and is not needed anyway.

### PR DESCRIPTION
**Pull request by allight**
Tested: modify xls to pull from this git and `bazel build -c opt //xls/modules/rle:rle_dec_gds_sky130`

### CODE REVIEW

**Comment by allight** [comment]
@QuantamHD @grebe @hzeller

**Comment by hzeller** [comment]
(not sure how I can trigger the CI, @QuantamHD might be able to)

**Comment by allight** [comment]
/gcbrun was what he did before? Maybe need to have approvers.

**Pull request merged**
