### PR TITLE
Simplify m4 and bison rules with "org_gnu_gnulib" and fixup "tk_tcl" build

### PR DESCRIPTION
**Pull request by jesec**
Can be used by GNU tools like m4 and bison.

This change consolidates the portability and Bazel works of GNU tools
into a unified place, in effect offloads the HARD parts from them.
Hopefully, this will make it easier for us to maintain rules of those
tools.

Plus, this version of gnulib is fairly recent, which provides much
better compatibility.

Most of the rule comes from https://github.com/jmillikin/rules_m4,
which is licensed under Apache 2.0.

### CODE REVIEW

**Comment by jesec** [comment]
```
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_tuxfamily_eigen:
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Well. Not my fault. Is there a way to rerun? 

/gcbrun

?

**Comment by hzeller** [comment]
Did you verify that bison can be built under MacOS ? In verible, we once [switched to](https://github.com/google/verible/pull/728) the jmillikin rules to get a working compilation across platforms (as there were otherwise all kinds of troubles with gnulib and m4); just want to make sure that these jmillikin-derived rules preserve that property.

**Comment by jesec** [comment]
> Did you verify that bison can be built under MacOS ? In verible, we once [switched to](https://github.com/google/verible/pull/728) the jmillikin rules to get a working compilation across platforms (as there were otherwise all kinds of troubles with gnulib and m4); just want to make sure that these jmillikin-derived rules preserve that property.

At the moment, I can't say for sure about macOS support with this PR. 

However, I am fairly sure that the rules (w/o this PR) do not work for macOS right now. This PR brings substantial portability improvement, and we can certainly try to further improve to support macOS in the future.

**Comment by jesec** [comment]
I manage to test on a macOS machine. With this PR, it is indeed possible to compile working `bison` and `m4` executable on macOS. 

image

**Review by hzeller — APPROVED** [review]
Nice!
For the question of portability, maybe for later we can consider CIs that run on a mac/windows environment.

**Comment by jesec** [comment]
Bump! 

Can someone 🚢 this?

**Comment by mithro** [comment]
Should this be merged? @QuantamHD

**Comment by QuantamHD** [comment]
Sorry for the late reply @jesec merging now.

**Pull request merged**
